<?php

declare(strict_types=1);
use Tests\Support\CompatibilityLedger; use Tests\Support\PhpSourceScanner;
$root=dirname(__DIR__,2);$checks=0;$pass=static function(bool$c,string$m)use(&$checks):void{if(!$c){fwrite(STDERR,'[FAIL] '.$m.PHP_EOL);exit(1);}++$checks;echo'[PASS] '.$m.PHP_EOL;};
$targets=['gulliver/system/class.templatePower.php','gulliver/system/class.xmlformExtension.php','gulliver/system/class.xmlformSafeExpressionEvaluator.php'];$required=array_merge($targets,['tests/fixtures/deprecation-budget.json','tests/fixtures/eval-inventory.json','tests/unit/Compatibility/GulliverFinalEvalMigrationTest.php','tests/tools/verify-u313.php','tests/tools/run-u313-checks.cmd']);foreach($required as$r)$pass(is_file($root.'/'.$r),'Required U-3.13 file: '.$r);$pass(hash_file('sha256',$root.'/composer.json')==='708119e1eb1f15b263a35366ff18116dcd828329f2481aa588efc49d81a33ad2','Unchanged since U-1: composer.json');$pass(hash_file('sha256',$root.'/composer.lock')==='c6d4c0da3da7483ad9499f8fdc5a137997cf57a55b1bbeee09f8210711a4c50f','Unchanged since U-1: composer.lock');require_once $root.'/tests/bootstrap.php';require_once $root.'/gulliver/system/class.xmlformSafeExpressionEvaluator.php';$pattern='(?<![\\w$>-])eval\\s*\\(';
foreach($targets as$f){$raw=PhpSourceScanner::read($root.'/'.$f);token_get_all($raw,TOKEN_PARSE);$pass(PhpSourceScanner::matchCount(PhpSourceScanner::codeOnlySource($raw),$pattern)===0,$f.' parses and has no executable eval');}
$pass(XmlFormSafeExpressionEvaluator::evaluate("'' == ''"),'Empty CellMark value matches empty literal');$pass(!XmlFormSafeExpressionEvaluator::evaluate("'2026-09-14' == ''"),'Populated CellMark value does not match empty literal');$pass(XmlFormSafeExpressionEvaluator::evaluate('(2 + 3 * 4) == 14'),'Arithmetic precedence is preserved');$pass(XmlFormSafeExpressionEvaluator::evaluate('true xor false'),'Boolean xor is supported');$pass(!XmlFormSafeExpressionEvaluator::evaluate("system('id')"),'Function-call syntax fails closed');$pass(!XmlFormSafeExpressionEvaluator::evaluate('$GLOBALS'),'Variable syntax fails closed');$x=PhpSourceScanner::read($root.'/gulliver/system/class.xmlformExtension.php');$pass(substr_count($x,'XmlFormSafeExpressionEvaluator::evaluate($value);')===2,'Both CellMark methods use the shared evaluator');
$t=PhpSourceScanner::read($root.'/gulliver/system/class.templatePower.php');$pass(strpos($t,'$temporaryScript = tmpfile();')!==false,'Inline TemplatePower script uses an OS-owned temporary file');$pass(strpos($t,"include \$temporaryScriptMetadata['uri'];")!==false,'Temporary script executes through include');$pass(strpos($t,'finally {')!==false&&strpos($t,'fclose($temporaryScript);')!==false,'Temporary resource closes in finally');
require_once $root.'/gulliver/system/class.templatePower.php';$parser=new TemplatePower("<!-- INCLUDESCRIPT BLOCK : sample -->\r\n",T_BYVAR);$parser->assignInclude('sample',"before<?php echo strtoupper('ok'); ?>after",T_BYVAR);$parser->prepare();$pass(strpos($parser->getOutputContent(),'beforeOKafter')!==false,'Inline TemplatePower script preserves buffered output');
$b=json_decode((string)file_get_contents($root.'/tests/fixtures/deprecation-budget.json'),true,512,JSON_THROW_ON_ERROR);$i=json_decode((string)file_get_contents($root.'/tests/fixtures/eval-inventory.json'),true,512,JSON_THROW_ON_ERROR);$c=CompatibilityLedger::counts($b['scope'],['eval'=>$pattern]);$pass(($b['_noteU313']??'')!=='','U-3.13 ratchet movement is documented');$pass($b['budgets']['eval']===0&&$c['eval']['textual']===0,'Textual eval budget and live count are 44');$pass($b['codeBudgets']['eval']===0&&$c['eval']['code']===0,'Executable eval budget and live count are 32');$pass($i['summary']['textual']===0&&$i['summary']['executable']===0,'Inventory matches 44 textual / 32 executable');$pass($i['summary']['nonExecutable']===0,'Non-executable eval count remains 12');$pass($i['summary']['executableFiles']===0,'Executable eval files lowered to 4');$pass(($i['categories']['gulliver_dynamic_runtime']['count']??null)===0,'Gulliver dynamic runtime category is zero');foreach(array_slice($targets,0,2)as$f)$pass(!array_key_exists($f,$i['perFileExecutable']),$f.' absent from executable inventory');$pass($b['budgets']['strftime']===140&&$b['codeBudgets']['strftime']===0,'Strftime ratchet unchanged');$pass($b['budgets']['utf8_encode_decode']===4&&$b['codeBudgets']['utf8_encode_decode']===0,'UTF-8 ratchet unchanged');echo'[SUMMARY] '.$checks.' U-3.13 preflight checks passed.'.PHP_EOL;
