<?php

declare(strict_types=1);
use Tests\Support\CompatibilityLedger; use Tests\Support\PhpSourceScanner;
$root=dirname(__DIR__,2);$checks=0;$pass=static function(bool$c,string$m)use(&$checks):void{if(!$c){fwrite(STDERR,'[FAIL] '.$m.PHP_EOL);exit(1);}++$checks;echo'[PASS] '.$m.PHP_EOL;};
$targets=['gulliver/system/class.bootstrap.php','gulliver/system/class.g.php','gulliver/system/class.webResource.php'];$required=array_merge($targets,['tests/fixtures/deprecation-budget.json','tests/fixtures/eval-inventory.json','tests/unit/Compatibility/GulliverDirectDispatchEvalMigrationTest.php','tests/tools/verify-u312.php','tests/tools/run-u312-checks.cmd']);foreach($required as$r)$pass(is_file($root.'/'.$r),'Required U-3.12 file: '.$r);
$pass(hash_file('sha256',$root.'/composer.json')==='b3f0ff9a9882690f210fec2c8106175b47bed82f0aea1de035873a2d12295f0a','Unchanged since U-1: composer.json');$pass(hash_file('sha256',$root.'/composer.lock')==='085ed0f8c619f302684dd8daba5dd65b5a47b4572aaf092731fefea30e15418c','Unchanged since U-1: composer.lock');require_once $root.'/tests/bootstrap.php';$pattern='(?<![\\w$>-])eval\\s*\\(';
foreach($targets as$f){$raw=PhpSourceScanner::read($root.'/'.$f);token_get_all($raw,TOKEN_PARSE);$pass(PhpSourceScanner::matchCount(PhpSourceScanner::codeOnlySource($raw),$pattern)===0,$f.' has no executable eval site');}
$braw=PhpSourceScanner::read($root.'/'.$targets[0]);$pass(substr_count($braw,'global ${$translationVariable};')===2,'Both plugin-language branches bind the dynamic translation global');$pass(strpos($braw,'Bootstrap::json_encode(${$translationVariable})')!==false,'Typed translation output reads the dynamic variable directly');
$graw=PhpSourceScanner::read($root.'/'.$targets[1]);$pass(strpos($graw,'$strAux = call_user_func($callable, $argument);')!==false,'replaceDataField function token uses call_user_func');$pass(strpos($graw,'$msg .= $_SESSION[$token];')!==false,'Message token reads the session directly');$pass(strpos($graw,'$existId = isset($GLOBALS[$translationVariable][$msgID]);')!==false,'Plugin translation existence uses GLOBALS');$pass(strpos($graw,'$GLOBALS[$translationVariable][$msgID]')!==false,'Plugin translation value uses GLOBALS');
$wraw=PhpSourceScanner::read($root.'/'.$targets[2]);$pass(strpos($wraw,'$arguments[] = &$parameters[$key];')!==false,'WebResource preserves reference-capable positional arguments');$pass(strpos($wraw,"\$res = call_user_func_array(array(\$this, \$post['function']), \$arguments);")!==false,'WebResource dispatch uses call_user_func_array');$pass(strpos($wraw,'$paramsRef')===false,'WebResource generated parameter expressions were removed');
$b=json_decode((string)file_get_contents($root.'/tests/fixtures/deprecation-budget.json'),true,512,JSON_THROW_ON_ERROR);$i=json_decode((string)file_get_contents($root.'/tests/fixtures/eval-inventory.json'),true,512,JSON_THROW_ON_ERROR);$c=CompatibilityLedger::counts($b['scope'],['eval'=>$pattern]);$pass(($b['_noteU312']??'')!=='','U-3.12 ratchet movement is documented');$pass($b['budgets']['eval']===0,'Eval textual budget lowered to 19');$pass($b['codeBudgets']['eval']===0,'Eval executable budget lowered to 7');$pass($c['eval']['textual']===0,'Live textual eval count is 19');$pass($c['eval']['code']===0,'Live executable eval count is 7');$pass($i['summary']['textual']===0,'Inventory textual count is 44');$pass($i['summary']['executable']===0,'Inventory executable count is 32');$pass($i['summary']['nonExecutable']===0,'Non-executable eval count remains 12');$pass($i['summary']['executableFiles']===0,'Executable eval files lowered to 4');$pass(($i['categories']['gulliver_dynamic_runtime']['count']??null)===0,'Gulliver dynamic runtime lowered to 0');foreach($targets as$f){$pass(!array_key_exists($f,$i['perFileExecutable']),$f.' absent from per-file inventory');}$pass($b['budgets']['strftime']===140&&$b['codeBudgets']['strftime']===0,'Strftime ratchet unchanged');$pass($b['budgets']['utf8_encode_decode']===4&&$b['codeBudgets']['utf8_encode_decode']===0,'UTF-8 ratchet unchanged');echo'[SUMMARY] '.$checks.' U-3.12 preflight checks passed.'.PHP_EOL;
