<?php

declare(strict_types=1);
use Tests\Support\CompatibilityLedger; use Tests\Support\PhpSourceScanner;
$root=dirname(__DIR__,2);$checks=0;$pass=static function(bool $c,string $m)use(&$checks):void{if(!$c){fwrite(STDERR,'[FAIL] '.$m.PHP_EOL);exit(1);}++$checks;echo '[PASS] '.$m.PHP_EOL;};
$required=['gulliver/system/class.xmlform.php','tests/fixtures/deprecation-budget.json','tests/fixtures/eval-inventory.json','tests/unit/Compatibility/XmlFormEvalMigrationTest.php','tests/tools/verify-u311.php','tests/tools/run-u311-checks.cmd'];foreach($required as$r)$pass(is_file($root.'/'.$r),'Required U-3.11 file: '.$r);
$pass(hash_file('sha256',$root.'/composer.json')==='708119e1eb1f15b263a35366ff18116dcd828329f2481aa588efc49d81a33ad2','Unchanged since U-1: composer.json');$pass(hash_file('sha256',$root.'/composer.lock')==='9f879af7b047666ee70708741d74521c91925e1b6addd80a9d465b6ea76e9cb3','Accepted T-2B rev E Composer lock');require_once $root.'/tests/bootstrap.php';
$target='gulliver/system/class.xmlform.php';$pattern='(?<![\\w$>-])eval\\s*\\(';$raw=PhpSourceScanner::read($root.'/'.$target);$code=PhpSourceScanner::codeOnlySource($raw);$b=json_decode((string)file_get_contents($root.'/tests/fixtures/deprecation-budget.json'),true,512,JSON_THROW_ON_ERROR);$i=json_decode((string)file_get_contents($root.'/tests/fixtures/eval-inventory.json'),true,512,JSON_THROW_ON_ERROR);$c=CompatibilityLedger::counts($b['scope'],['eval'=>$pattern]);token_get_all($raw,TOKEN_PARSE);$pass(true,'class.xmlform.php parses under PHP 8.1');$pass(PhpSourceScanner::matchCount($code,$pattern)===0,'XmlForm contains no executable eval sites');
foreach(['DBC_SERVER'=>'HOST','DBC_USERNAME'=>'USER','DBC_PASSWORD'=>'PASS','DBC_DATABASE'=>'NAME','DBC_TYPE'=>'TYPE']as$f=>$s){$pass(strpos($raw,"\$res['{$f}'] = constant('DB_' . \$this->sqlConnection . '_{$s}');")!==false,'Dynamic '.$s.' constant uses constant()');$pass(strpos($raw,"defined('DB_' . \$this->sqlConnection . '_{$s}')")!==false,'Existing '.$s.' defined() gate is preserved');}$pass(PhpSourceScanner::matchCount($code,'(?<![\\w$>-])constant\\s*\\(')===5,'XmlForm has exactly five dynamic constant reads');$pass(substr_count($raw,'$this->{$key} = $v;')>=2,'Both migrated XML attribute assignments use native variable properties');
$pass(($b['_noteU311']??'')!=='','U-3.11 ratchet movement is documented');$pass($b['budgets']['eval']===0,'Eval textual budget lowered to 19');$pass($b['codeBudgets']['eval']===0,'Eval executable budget lowered to 7');$pass($c['eval']['textual']===0,'Live textual eval count is 19');$pass($c['eval']['code']===0,'Live executable eval count is 7');$pass($i['summary']['textual']===0,'Inventory textual eval count is 19');$pass($i['summary']['executable']===0,'Inventory executable eval count is 7');$pass($i['summary']['nonExecutable']===0,'Inventory non-executable eval count remains 12');$pass($i['summary']['executableFiles']===0,'Inventory executable file count lowered to 4');$pass(($i['categories']['gulliver_dynamic_runtime']['count']??null)===0,'Gulliver dynamic runtime category lowered to 0');$pass(!array_key_exists($target,$i['perFileExecutable']),'XmlForm absent from per-file inventory');$pass(count(array_filter($i['executableSites'],static fn(array $s):bool=>$s['file']===$target))===0,'XmlForm has no listed eval site');echo '[SUMMARY] '.$checks.' U-3.11 preflight checks passed.'.PHP_EOL;
