<?php

declare(strict_types=1);
use Tests\Support\CompatibilityLedger; use Tests\Support\PhpSourceScanner;
$root=dirname(__DIR__,2);$checks=0;$pass=static function(bool$c,string$m)use(&$checks):void{if(!$c){fwrite(STDERR,'[FAIL] '.$m.PHP_EOL);exit(1);}++$checks;echo'[PASS] '.$m.PHP_EOL;};
$targets=['workflow/engine/classes/PropelTable.php','workflow/engine/classes/model/Language.php','workflow/engine/classes/model/ListInbox.php','workflow/engine/classes/model/ListParticipatedLast.php','workflow/engine/src/ProcessMaker/BusinessModel/Consolidated.php','workflow/engine/src/ProcessMaker/BusinessModel/ReportTable.php','workflow/engine/src/ProcessMaker/BusinessModel/Table.php'];$required=array_merge($targets,['tests/fixtures/deprecation-budget.json','tests/fixtures/eval-inventory.json','tests/unit/Compatibility/DynamicModelDispatchEvalMigrationTest.php','tests/tools/verify-u314.php','tests/tools/run-u314-checks.cmd']);foreach($required as$r)$pass(is_file($root.'/'.$r),'Required U-3.14 file: '.$r);$pass(hash_file('sha256',$root.'/composer.json')==='708119e1eb1f15b263a35366ff18116dcd828329f2481aa588efc49d81a33ad2','Unchanged since U-1: composer.json');$pass(hash_file('sha256',$root.'/composer.lock')==='9f879af7b047666ee70708741d74521c91925e1b6addd80a9d465b6ea76e9cb3','Accepted T-2B rev E Composer lock');require_once $root.'/tests/bootstrap.php';$pattern='(?<![\\w$>-])eval\\s*\\(';
foreach($targets as$f){$raw=PhpSourceScanner::read($root.'/'.$f);token_get_all($raw,TOKEN_PARSE);$pass(PhpSourceScanner::matchCount(PhpSourceScanner::codeOnlySource($raw),$pattern)===0,$f.' parses and has no executable eval');}
$p=PhpSourceScanner::read($root.'/'.$targets[0]);$pass(strpos($p,'settype($value, gettype($this->{$atrib}));')!==false&&strpos($p,'$this->{$atrib} = $value;')!==false,'PropelTable preserves typed variable-property assignment');$l=PhpSourceScanner::read($root.'/'.$targets[1]);$pass(strpos($l,'$translatedText = ${$translationVariable};')!==false,'Language reads the included variable dynamically');$li=PhpSourceScanner::read($root.'/'.$targets[2]);$pass(substr_count($li,"constant('AppDelegationPeer::' . ")===2,'ListInbox resolves both peer fields via constant()');$lp=PhpSourceScanner::read($root.'/'.$targets[3]);$pass(strpos($lp,"constant('ListParticipatedLastPeer::' . \$k)")!==false,'ListParticipatedLast resolves set fields via constant()');$co=PhpSourceScanner::read($root.'/'.$targets[4]);$pass(substr_count($co,'$field = constant(')===3,'Consolidated resolves three search/sort peer constants');$rt=PhpSourceScanner::read($root.'/'.$targets[5]);$pass(strpos($rt,"constant(\$additionalTableClassPeerName . '::DATABASE_NAME')")!==false&&strpos($rt,'new $additionalTableClassName()')!==false,'ReportTable uses native database constant and construction');$ta=PhpSourceScanner::read($root.'/'.$targets[6]);$pass(substr_count($ta,"call_user_func_array(array(\$classPeerName, 'retrieveByPk'), \$params)")===2,'Table preserves both composite-key dispatch paths');$pass(substr_count($ta,"\$property = str_replace('fld', 'field', \$key);")===2,'Table has both native dynamic-property paths');$pass(strpos($ta,"constant(\$classPeerName . '::DATABASE_NAME')")!==false,'Table resolves the dynamic database constant');
$b=json_decode((string)file_get_contents($root.'/tests/fixtures/deprecation-budget.json'),true,512,JSON_THROW_ON_ERROR);$i=json_decode((string)file_get_contents($root.'/tests/fixtures/eval-inventory.json'),true,512,JSON_THROW_ON_ERROR);$c=CompatibilityLedger::counts($b['scope'],['eval'=>$pattern]);$pass(($b['_noteU314']??'')!=='','U-3.14 ratchet movement is documented');$pass($b['budgets']['eval']===0&&$c['eval']['textual']===0,'Textual eval budget and live count are 19');$pass($b['codeBudgets']['eval']===0&&$c['eval']['code']===0,'Executable eval budget and live count are 7');$pass($i['summary']['textual']===0&&$i['summary']['executable']===0,'Inventory matches 19 textual / 7 executable');$pass($i['summary']['nonExecutable']===0,'Non-executable eval count remains 12');$pass($i['summary']['executableFiles']===0,'Executable eval files lowered to 4');$pass(($i['categories']['dynamic_model_or_criteria']['count']??null)===0,'Dynamic model/criteria category lowered to 5');foreach($targets as$f)$pass(!array_key_exists($f,$i['perFileExecutable']),$f.' absent from executable inventory');$pass(($i['categories']['gulliver_dynamic_runtime']['count']??null)===0,'Gulliver runtime remains zero');$pass($b['budgets']['strftime']===140&&$b['codeBudgets']['strftime']===0,'Strftime ratchet unchanged');$pass($b['budgets']['utf8_encode_decode']===4&&$b['codeBudgets']['utf8_encode_decode']===0,'UTF-8 ratchet unchanged');echo'[SUMMARY] '.$checks.' U-3.14 preflight checks passed.'.PHP_EOL;
