<?php

declare(strict_types=1);
$root=dirname(__DIR__,2);
require_once $root.'/tests/bootstrap.php';
require_once $root.'/workflow/engine/classes/XMLWhereExpressionEvaluator.php';
require_once $root.'/workflow/engine/src/ProcessMaker/BusinessModel/LegacyArrayLiteralParser.php';
require_once $root.'/gulliver/system/class.xmlformSafeExpressionEvaluator.php';
use Tests\Support\PhpSourceScanner;
use Tests\Support\CompatibilityLedger;
$checks=0;$pass=static function($ok,$message)use(&$checks){if(!$ok){fwrite(STDERR,'[FAIL] '.$message.PHP_EOL);exit(1);}$checks++;echo'[PASS] '.$message.PHP_EOL;};
$targets=['workflow/engine/classes/XMLConnection.php','workflow/engine/classes/model/Event.php','workflow/engine/src/ProcessMaker/BusinessModel/Process.php'];$pattern='(?<![\\w$>-])eval\\s*\\(';
foreach($targets as$f){$s=PhpSourceScanner::read($root.'/'.$f);$pass(PhpSourceScanner::matchCount(PhpSourceScanner::codeOnlySource($s),$pattern)===0,$f.' has no executable eval');}
$xml=PhpSourceScanner::read($root.'/'.$targets[0]);$pass(substr_count($xml,'XMLWhereExpressionEvaluator::evaluate($sqlWhereExpression, $res[$r])')===3,'All three XML WHERE paths use shared evaluator');$pass(XMLWhereExpressionEvaluator::evaluate("STATUS = 'OPEN' AND TOTAL >= 2",['STATUS'=>'OPEN','TOTAL'=>3]),'XML equality, AND and comparison behavior');$pass(XMLWhereExpressionEvaluator::evaluate("NAME LIKE 'ab%'",['NAME'=>'ABcd']),'XML LIKE behavior');$pass(!XMLWhereExpressionEvaluator::evaluate("system('id')",[]),'XML calls fail closed');$pass(!XMLWhereExpressionEvaluator::evaluate('MISSING = 1',[]),'XML missing fields fail closed');
$event=PhpSourceScanner::read($root.'/'.$targets[1]);$pass(strpos($event,'XmlFormSafeExpressionEvaluator::evaluate($sCondition)')!==false,'Event uses shared literal evaluator');$pass(XmlFormSafeExpressionEvaluator::evaluate('(2 + 3) * 4 == 20'),'Event arithmetic behavior');$pass(!XmlFormSafeExpressionEvaluator::evaluate("strlen('x')"),'Event calls fail closed');
$process=PhpSourceScanner::read($root.'/'.$targets[2]);$pass(strpos($process,'LegacyArrayLiteralParser::parse($fieldValue)')!==false,'Process uses array literal parser');$pass(\ProcessMaker\BusinessModel\LegacyArrayLiteralParser::parse("array('A','B')")===['A','B'],'Long array behavior');$pass(\ProcessMaker\BusinessModel\LegacyArrayLiteralParser::parse("['k'=>[1,2]]")===['k'=>[1,2]],'Nested associative behavior');$pass(\ProcessMaker\BusinessModel\LegacyArrayLiteralParser::parse("system('id')")===null,'Executable array input fails closed');
$b=json_decode((string)file_get_contents($root.'/tests/fixtures/deprecation-budget.json'),true,512,JSON_THROW_ON_ERROR);$i=json_decode((string)file_get_contents($root.'/tests/fixtures/eval-inventory.json'),true,512,JSON_THROW_ON_ERROR);$c=CompatibilityLedger::counts($b['scope'],['eval'=>$pattern]);$pass(($b['_noteU316']??'')!=='','U-3.16 ratchet is documented');$pass($b['budgets']['eval']===0&&$c['eval']['textual']===0,'Textual eval count is 14');$pass($b['codeBudgets']['eval']===0&&$c['eval']['code']===0,'Executable eval count is 2');$pass($i['summary']['textual']===0&&$i['summary']['executable']===0&&$i['summary']['nonExecutable']===0,'Inventory matches 14/2/12');$pass($i['summary']['executableFiles']===0,'Only one executable eval file remains');$pass(($i['categories']['dynamic_model_or_criteria']['count']??null)===0,'Dynamic expression category is zero');$pass(($i['categories']['trigger_script_eval']['count']??null)===0,'Trigger category is zero');$pass($i['perFileExecutable']===[]&&$i['executableSites']===[],'Executable inventory is empty');echo'[SUMMARY] '.$checks.' U-3.16 preflight checks passed.'.PHP_EOL;
