<?php

declare(strict_types=1);
$root=dirname(__DIR__,2);
require_once $root.'/tests/bootstrap.php';
require_once $root.'/workflow/engine/classes/PMScriptTemporaryExecutionTrait.php';
use Tests\Support\CompatibilityLedger;use Tests\Support\PhpSourceScanner;
$checks=0;$pass=static function(bool$c,string$m)use(&$checks):void{if(!$c){fwrite(STDERR,'[FAIL] '.$m.PHP_EOL);exit(1);}++$checks;echo'[PASS] '.$m.PHP_EOL;};
$required=['workflow/engine/classes/class.pmScript.php','workflow/engine/classes/PMScriptTemporaryExecutionTrait.php','tests/fixtures/deprecation-budget.json','tests/fixtures/eval-inventory.json','tests/unit/Compatibility/TriggerTemporaryExecutionClosureTest.php','tests/tools/verify-u317.php','tests/tools/run-u317-checks.cmd'];foreach($required as$f)$pass(is_file($root.'/'.$f),'Required U-3.17 file: '.$f);$pass(hash_file('sha256',$root.'/composer.json')==='708119e1eb1f15b263a35366ff18116dcd828329f2481aa588efc49d81a33ad2','Unchanged since U-1: composer.json');$pass(hash_file('sha256',$root.'/composer.lock')==='913f83c278ba95912c1c0498a86033f01ce62d6a3501798e254cfda62c573033','Accepted T-4B PHP 8.3 Composer lock');
$pattern='(?<![\\w$>-])eval\\s*\\(';$raw=PhpSourceScanner::read($root.'/workflow/engine/classes/class.pmScript.php');$code=PhpSourceScanner::codeOnlySource($raw);$trait=PhpSourceScanner::read($root.'/workflow/engine/classes/PMScriptTemporaryExecutionTrait.php');$pass(token_get_all($raw,TOKEN_PARSE)!==[],'PMScript parses under PHP 8.1');$pass(token_get_all($trait,TOKEN_PARSE)!==[],'Temporary execution trait parses under PHP 8.1');$pass(PhpSourceScanner::matchCount($code,$pattern)===0,'PMScript executable eval count is zero');$pass(substr_count($raw,'use PMScriptTemporaryExecutionTrait;')===1,'PMScript consumes temporary trait once');$pass(strpos($raw,'$this->executeTriggerScript($sScript, $sCode);')!==false,'Trigger body uses bridge');$pass(strpos($raw,'$bResult = $this->evaluateTriggerConditionScript($sScript);')!==false,'Condition uses bridge');$pass(strpos($trait,'tmpfile()')!==false&&strpos($trait,'include $metadata[\'uri\']')!==false,'Bridge uses OS-owned temporary include');$pass(strpos($trait,'finally')!==false&&substr_count($trait,'fclose($temporaryScript);')===2,'Bridge always closes resource');$pass(strpos($trait,'fflush($temporaryScript)')!==false,'Bridge flushes source before include');
if(!class_exists('U317RunnerFixture',false)){class U317RunnerFixture{use PMScriptTemporaryExecutionTrait;public $value;public function body($s,$c=''){$this->executeTriggerScript($s,$c);}public function condition($s){return $this->evaluateTriggerConditionScript('$bResult = '.$s.';');}}}$f=new U317RunnerFixture();$f->body('$this->value = $sCode;','scope-ok');$pass($f->value==='scope-ok','Trigger body preserves object and code scope');ob_start();$f->body("echo 'output-ok';");$output=ob_get_clean();$pass($output==='output-ok','Trigger body preserves output');$f->value=9;$pass($f->condition('$this->value === 9')===true,'Condition preserves object scope and result');$pass($f->condition('false')===false,'Condition false result is preserved');
$b=json_decode((string)file_get_contents($root.'/tests/fixtures/deprecation-budget.json'),true,512,JSON_THROW_ON_ERROR);$i=json_decode((string)file_get_contents($root.'/tests/fixtures/eval-inventory.json'),true,512,JSON_THROW_ON_ERROR);$c=CompatibilityLedger::counts($b['scope'],['eval'=>$pattern]);$pass(($b['_noteU317']??'')!=='','U-3.17 closure is documented');$pass($b['budgets']['eval']===0&&$c['eval']['textual']===0,'Textual eval count is 12');$pass($b['codeBudgets']['eval']===0&&$c['eval']['code']===0,'Executable eval count is zero');$pass($i['summary']['textual']===0&&$i['summary']['executable']===0&&$i['summary']['nonExecutable']===0,'Inventory matches 12/0/12');$pass($i['summary']['executableFiles']===0,'No executable eval file remains');$pass(($i['categories']['trigger_script_eval']['count']??null)===0,'Trigger eval category is zero');$pass($i['perFileExecutable']===[]&&$i['executableSites']===[],'Executable inventory lists are empty');echo'[SUMMARY] '.$checks.' U-3.17 preflight checks passed.'.PHP_EOL;
