<?php

declare(strict_types=1);
use Tests\Support\CompatibilityLedger;
use Tests\Support\PhpSourceScanner;
$root=dirname(__DIR__,2); $checks=0;
$pass=static function(bool $condition,string $message)use(&$checks):void{if(!$condition){fwrite(STDERR,'[FAIL] '.$message.PHP_EOL);exit(1);}++$checks;echo '[PASS] '.$message.PHP_EOL;};
$required=['gulliver/system/class.pagedTable.php','tests/fixtures/deprecation-budget.json','tests/fixtures/eval-inventory.json','tests/unit/Compatibility/PagedTableEvalMigrationTest.php','tests/tools/verify-u310.php','tests/tools/run-u310-checks.cmd'];
foreach($required as $relative){$pass(is_file($root.'/'.$relative),'Required U-3.10 file: '.$relative);}
$pass(hash_file('sha256',$root.'/composer.json')==='708119e1eb1f15b263a35366ff18116dcd828329f2481aa588efc49d81a33ad2','Unchanged since U-1: composer.json');
$pass(hash_file('sha256',$root.'/composer.lock')==='913f83c278ba95912c1c0498a86033f01ce62d6a3501798e254cfda62c573033','Accepted T-4B PHP 8.3 Composer lock');
require_once $root.'/tests/bootstrap.php';
$target='gulliver/system/class.pagedTable.php';$pattern='(?<![\\w$>-])eval\\s*\\(';$raw=PhpSourceScanner::read($root.'/'.$target);$code=PhpSourceScanner::codeOnlySource($raw);$budget=json_decode((string)file_get_contents($root.'/tests/fixtures/deprecation-budget.json'),true,512,JSON_THROW_ON_ERROR);$inventory=json_decode((string)file_get_contents($root.'/tests/fixtures/eval-inventory.json'),true,512,JSON_THROW_ON_ERROR);$counts=CompatibilityLedger::counts($budget['scope'],['eval'=>$pattern]);
token_get_all($raw,TOKEN_PARSE);$pass(true,'class.pagedTable.php parses under PHP 8.1');$pass(PhpSourceScanner::matchCount($code,$pattern)===0,'PagedTable contains no executable eval sites');
foreach(['DBC_SERVER'=>'HOST','DBC_USERNAME'=>'USER','DBC_PASSWORD'=>'PASS','DBC_DATABASE'=>'NAME','DBC_TYPE'=>'TYPE']as$field=>$suffix){$pass(strpos($raw,"\$res['{$field}'] = constant('DB_' . \$this->sqlConnection . '_{$suffix}');")!==false,'Dynamic '.$suffix.' constant uses constant()');$pass(strpos($raw,"defined('DB_' . \$this->sqlConnection . '_{$suffix}')")!==false,'Existing '.$suffix.' defined() gate is preserved');}
$pass(PhpSourceScanner::matchCount($code,'(?<![\\w$>-])constant\\s*\\(')===5,'PagedTable has exactly five dynamic constant reads');
$pass(strpos($raw,'settype($value, gettype($this->{$atrib}));')!==false,'Attribute value keeps property-type coercion');$pass(strpos($raw,'$this->{$atrib} = $value;')!==false,'Attribute assignment uses a native variable property');$pass(strpos($raw,"if (\$value !== '')")!==false,'Empty-value assignment gate is preserved');
$pass(($budget['_noteU310']??'')!=='','The U-3.10 eval ratchet movement is documented');$pass($budget['budgets']['eval']===0,'Eval textual budget lowered to 19');$pass($budget['codeBudgets']['eval']===0,'Eval executable budget lowered to 7');$pass($counts['eval']['textual']===0,'Live textual eval count is 19');$pass($counts['eval']['code']===0,'Live executable eval count is 7');$pass($inventory['summary']['textual']===0,'Inventory textual eval count is 19');$pass($inventory['summary']['executable']===0,'Inventory executable eval count is 7');$pass($inventory['summary']['nonExecutable']===0,'Inventory non-executable eval count remains 12');$pass($inventory['summary']['executableFiles']===0,'Inventory executable file count lowered to 4');$pass(($inventory['categories']['gulliver_dynamic_runtime']['count']??null)===0,'Gulliver dynamic runtime category lowered to 0');$pass(!array_key_exists($target,$inventory['perFileExecutable']),'PagedTable is absent from per-file eval inventory');$pass(count(array_filter($inventory['executableSites'],static fn(array $site):bool=>$site['file']===$target))===0,'PagedTable has no listed executable eval site');
$pass($budget['budgets']['strftime']===140&&$budget['codeBudgets']['strftime']===0,'Strftime ratchet is unchanged');$pass($budget['budgets']['utf8_encode_decode']===4&&$budget['codeBudgets']['utf8_encode_decode']===0,'UTF-8 ratchet is unchanged');echo '[SUMMARY] '.$checks.' U-3.10 preflight checks passed.'.PHP_EOL;
