<?php
/** Fail-closed evaluator for the legacy XML adapter SQL WHERE subset. */
final class XMLWhereExpressionEvaluator
{
 private $tokens=array(); private $position=0; private $row=array();
 public static function evaluate($expression,array $row){try{$t=self::tokenize((string)$expression);if($t===null||$t===array())return false;$p=new self($t,$row);$v=$p->parseOr();return $p->position===count($p->tokens)&&(bool)$v;}catch(Throwable $e){return false;}}
 private function __construct(array $t,array $r){$this->tokens=$t;$this->row=$r;}
 private static function tokenize($s){$t=array();$n=strlen($s);$i=0;while($i<$n){if(preg_match('/\\G\\s+/A',$s,$m,0,$i)){$i+=strlen($m[0]);continue;}$c=$s[$i];if($c==="'"||$c==='"'){$q=$c;$i++;$v='';$closed=false;while($i<$n){$c=$s[$i++];if($c===$q){if($i<$n&&$s[$i]===$q){$v.=$q;$i++;continue;}$closed=true;break;}if($c==='\\'&&$i<$n)$v.=$s[$i++];else$v.=$c;}if(!$closed)return null;$t[]=array('value',$v);continue;}if(preg_match('/\\G(?:\\d+\\.\\d+|\\d+)/A',$s,$m,0,$i)){$x=$m[0];$t[]=array('value',strpos($x,'.')===false?(int)$x:(float)$x);$i+=strlen($x);continue;}if(preg_match('/\\G[A-Za-z_][A-Za-z0-9_.]*/A',$s,$m,0,$i)){$w=$m[0];$u=strtoupper($w);if(in_array($u,array('AND','OR','NOT','LIKE'),true))$t[]=array('operator',$u);elseif($u==='TRUE'||$u==='FALSE'||$u==='NULL')$t[]=array('value',$u==='TRUE'?true:($u==='FALSE'?false:null));else$t[]=array('field',$w);$i+=strlen($w);continue;}$ok=false;foreach(array('<=','>=','<>','!=','==','=','<','>','(',')','+','-')as$o){if(substr($s,$i,strlen($o))===$o){$t[]=array('operator',$o);$i+=strlen($o);$ok=true;break;}}if(!$ok)return null;}return$t;}
 private function parseOr(){$v=$this->parseAnd();while($this->matches('OR')){$r=$this->parseAnd();$v=(bool)$v||(bool)$r;}return$v;}
 private function parseAnd(){$v=$this->parseNot();while($this->matches('AND')){$r=$this->parseNot();$v=(bool)$v&&(bool)$r;}return$v;}
 private function parseNot(){if($this->matches('NOT'))return!$this->parseNot();return$this->parseComparison();}
 private function parseComparison(){$l=$this->parseUnary();$neg=false;if($this->matches('NOT')){if(!$this->matches('LIKE'))throw new UnexpectedValueException('Expected LIKE');$o='LIKE';$neg=true;}else$o=$this->one(array('<=','>=','<>','!=','==','=','<','>','LIKE'));if($o===null)return$l;$r=$this->parseUnary();if($o==='LIKE'){$x=self::like($l,$r);return$neg?!$x:$x;}if($o==='='||$o==='==')return$l==$r;if($o==='<>'||$o==='!=')return$l!=$r;if($o==='<=')return$l<=$r;if($o==='>=')return$l>=$r;if($o==='<')return$l<$r;if($o==='>')return$l>$r;return false;}
 private function parseUnary(){if($this->matches('+'))return+$this->parseUnary();if($this->matches('-'))return-$this->parseUnary();if($this->matches('(')){$v=$this->parseOr();if(!$this->matches(')'))throw new UnexpectedValueException('Missing parenthesis');return$v;}if(!isset($this->tokens[$this->position]))throw new UnexpectedValueException('Expected value');$x=$this->tokens[$this->position++];if($x[0]==='value')return$x[1];if($x[0]==='field'){if(!array_key_exists($x[1],$this->row))throw new UnexpectedValueException('Unknown field');return$this->row[$x[1]];}throw new UnexpectedValueException('Expected value');}
 private static function like($v,$p){$q=preg_quote((string)$p,'/');return preg_match('/^'.str_replace('%','.*',$q).'$/im',(string)$v)===1;}
 private function matches($o){if(isset($this->tokens[$this->position])&&$this->tokens[$this->position][0]==='operator'&&$this->tokens[$this->position][1]===$o){$this->position++;return true;}return false;}
 private function one(array $a){foreach($a as$o)if($this->matches($o))return$o;return null;}
}
