<?php

declare(strict_types=1);
namespace Tests\Unit\Compatibility;
use PHPUnit\Framework\TestCase; use Tests\Support\CompatibilityLedger; use Tests\Support\PhpSourceScanner;
final class AdditionalTablesDispatchFixture { public const FIELD='fixture.FIELD'; public static function retrieveByPK($a,$b){return array($a,$b);} public static function doCount($criteria){return $criteria['count'];} }
final class AdditionalTablesEvalMigrationTest extends TestCase {
private const TARGET='workflow/engine/classes/model/AdditionalTables.php'; private const EVAL_PATTERN='(?<![\\w$>-])eval\\s*\\(';
private static function src():string{return PhpSourceScanner::read(PM_TEST_ROOT.'/'.self::TARGET);} private static function code():string{return PhpSourceScanner::codeOnlySource(self::src());}
public function testAdditionalTablesContainsNoExecutableEval():void{self::assertSame(0,PhpSourceScanner::matchCount(self::code(),self::EVAL_PATTERN));}
public function testDataCriteriaUsesDirectSelectColumns():void{$s=self::src();self::assertStringContainsString('$oCriteria->addSelectColumn("\'1\' AS DUMMY");',$s);self::assertStringContainsString("constant(\$sClassPeerName . '::' . \$aField['FLD_NAME'])",$s);}
public function testNumericCriteriaGuardUsesResolvedPeerConstant():void{$s=self::src();self::assertStringContainsString('-99999999999',$s);self::assertStringContainsString('Criteria::NOT_EQUAL',$s);}
public function testTypedSelectExpressionsUseDirectCriteriaApi():void{$s=self::src();self::assertStringContainsString("\$selectExpression = 'round(' . \$peerField . ', ' . \$precision . ')'",$s);self::assertStringContainsString("\$oCriteria->addAsColumn(\$aField['FLD_NAME'], \$selectExpression);",$s);self::assertStringContainsString('$oCriteria->addSelectColumn($peerField);',$s);}
public function testFilterOrChainIsBuiltWithoutGeneratedPhp():void{$s=self::src();self::assertStringContainsString('$criterionChain = null;',$s);self::assertStringContainsString('$criterion->addOr($criterionChain);',$s);self::assertStringContainsString('$oCriteria->add($criterionChain);',$s);}
public function testSearchAndChainPreservesAllComparators():void{$s=self::src();self::assertStringContainsString('$criterion->addAnd($criterionChain);',$s);foreach(['Criteria::EQUAL','Criteria::NOT_EQUAL','Criteria::LIKE','Criteria::NOT_LIKE']as$c)self::assertStringContainsString($c,$s);}
public function testDynamicCountsUseCallableDispatch():void{$s=self::src();self::assertSame(2,substr_count($s,"call_user_func(array(\$sClassPeerName, 'doCount'), \$oCriteria)"));}
public function testSortDirectionsUseDirectColumns():void{$s=self::src();self::assertStringContainsString('$oCriteria->addAscendingOrderByColumn($_POST[\'sort\']);',$s);self::assertStringContainsString("constant(\$sClassPeerName . '::' . \$_POST['sort'])",$s);self::assertStringContainsString('$oCriteria->addDescendingOrderByColumn($_POST[\'sort\']);',$s);}
public function testDynamicSelectUsesCallableDispatch():void{self::assertStringContainsString("call_user_func(array(\$sClassPeerName, 'doSelectRS'), \$oCriteria)",self::src());}
public function testDynamicSetterUsesNativeMethodInvocation():void{$s=self::src();self::assertStringContainsString("\$setter = 'set' . \$this->getPHPName(\$sKey);",$s);self::assertStringContainsString('$oClass->{$setter}($aFields[$sKey]);',$s);}
public function testCompositeKeysUseOrderedArgumentArrays():void{$s=self::src();self::assertSame(3,substr_count($s,"call_user_func_array(array(\$peerClass, 'retrieveByPK'), \$keyValues)"));self::assertStringContainsString('$keyValues = array_values($aKeys);',$s);self::assertStringContainsString("\$keyValues[] = \$aFields[\$aField['FLD_NAME']];",$s);}
public function testReportSyncUsesResolvedAppUidAndStaticSelect():void{$s=self::src();self::assertStringContainsString("constant(\$peerClass . '::APP_UID')",$s);self::assertStringContainsString("call_user_func(array(\$peerClass, 'doSelect'), \$c)",$s);}
public function testBothReportRecordPathsUseDynamicConstruction():void{self::assertSame(2,substr_count(self::src(),'$obj = new $className();'));}
public function testNativeDispatchPrimitivesPreserveValuesAndOrder():void{$peer=AdditionalTablesDispatchFixture::class;self::assertSame('fixture.FIELD',constant($peer.'::FIELD'));self::assertSame(array('a',9),call_user_func_array(array($peer,'retrieveByPK'),array('a',9)));self::assertSame(4,call_user_func(array($peer,'doCount'),array('count'=>4)));}
public function testRatchetDropsTwentyFiveAndInventoryRemovesTarget():void{$b=json_decode((string)file_get_contents(PM_TEST_ROOT.'/tests/fixtures/deprecation-budget.json'),true,512,JSON_THROW_ON_ERROR);$i=json_decode((string)file_get_contents(PM_TEST_ROOT.'/tests/fixtures/eval-inventory.json'),true,512,JSON_THROW_ON_ERROR);$c=CompatibilityLedger::counts($b['scope'],['eval'=>self::EVAL_PATTERN]);self::assertSame(0, $c['eval']['textual']);self::assertSame(0, $c['eval']['code']);self::assertSame(0, $b['budgets']['eval']);self::assertSame(0, $b['codeBudgets']['eval']);self::assertArrayHasKey('_noteU315',$b);self::assertSame(0, $i['summary']['executableFiles']);self::assertSame(0,$i['categories']['dynamic_model_or_criteria']['count']);self::assertArrayNotHasKey(self::TARGET,$i['perFileExecutable']);self::assertCount(0,array_filter($i['executableSites'],static fn(array$s):bool=>$s['file']===self::TARGET));}
}
