<?php

declare(strict_types=1);
namespace Tests\Unit\Compatibility;
use PHPUnit\Framework\TestCase; use Tests\Support\CompatibilityLedger; use Tests\Support\PhpSourceScanner;
final class DynamicModelDispatchFixture { public const DATABASE_NAME='fixture'; public static function retrieveByPk($a,$b){return array($a,$b);} }
final class DynamicModelDispatchEvalMigrationTest extends TestCase {
private const EVAL_PATTERN='(?<![\\w$>-])eval\\s*\\(';
private const TARGETS=['workflow/engine/classes/PropelTable.php','workflow/engine/classes/model/Language.php','workflow/engine/classes/model/ListInbox.php','workflow/engine/classes/model/ListParticipatedLast.php','workflow/engine/src/ProcessMaker/BusinessModel/Consolidated.php','workflow/engine/src/ProcessMaker/BusinessModel/ReportTable.php','workflow/engine/src/ProcessMaker/BusinessModel/Table.php'];
private static function src(string$f):string{return PhpSourceScanner::read(PM_TEST_ROOT.'/'.$f);} private static function code(string$f):string{return PhpSourceScanner::codeOnlySource(self::src($f));}
public function testAllSevenTargetsContainNoExecutableEval():void{foreach(self::TARGETS as$f)self::assertSame(0,PhpSourceScanner::matchCount(self::code($f),self::EVAL_PATTERN),$f);}
public function testPropelTableUsesNativeTypedVariableProperty():void{$s=self::src(self::TARGETS[0]);self::assertStringContainsString('settype($value, gettype($this->{$atrib}));',$s);self::assertStringContainsString('$this->{$atrib} = $value;',$s);}
public function testLanguageReadsIncludedTranslationVariableDirectly():void{$s=self::src(self::TARGETS[1]);self::assertStringContainsString("\$translationVariable = 'translation' . \$plugin;",$s);self::assertStringContainsString('$translatedText = ${$translationVariable};',$s);}
public function testListInboxResolvesPeerFieldsWithConstant():void{$s=self::src(self::TARGETS[2]);self::assertStringContainsString("constant('AppDelegationPeer::' . \$fieldName)",$s);self::assertStringContainsString("constant('AppDelegationPeer::' . \$k)",$s);self::assertStringContainsString('Criteria::EQUAL',$s);}
public function testListParticipatedLastResolvesSetFieldsWithConstant():void{$s=self::src(self::TARGETS[3]);self::assertStringContainsString("constant('ListParticipatedLastPeer::' . \$k)",$s);self::assertStringContainsString('$v, Criteria::EQUAL',$s);}
public function testConsolidatedUsesDynamicPeerConstantsForSearchAndSort():void{$s=self::src(self::TARGETS[4]);self::assertSame(3,substr_count($s,'$field = constant('));self::assertStringContainsString("constant('ListInboxPeer::' . \$sort)",$s);}
public function testReportTableUsesDynamicConstructionAndDatabaseConstant():void{$s=self::src(self::TARGETS[5]);self::assertStringContainsString("\\Propel::getConnection(constant(\$additionalTableClassPeerName . '::DATABASE_NAME'))",$s);self::assertStringContainsString('$obj = new $additionalTableClassName();',$s);}
public function testBusinessModelTableUsesNativeDynamicProperties():void{$s=self::src(self::TARGETS[6]);self::assertSame(2,substr_count($s,"\$property = str_replace('fld', 'field', \$key);"));self::assertStringContainsString('$temp->{$property} = $valCol;',$s);self::assertStringContainsString('$temp->{$property} = $col;',$s);}
public function testBusinessModelTableUsesDynamicClassAndConnectionConstant():void{$s=self::src(self::TARGETS[6]);self::assertStringContainsString('$obj = new $className();',$s);self::assertStringContainsString("Propel::getConnection(constant(\$classPeerName . '::DATABASE_NAME'))",$s);}
public function testCompositePrimaryKeysUseArgumentSafeDispatch():void{$s=self::src(self::TARGETS[6]);self::assertSame(2,substr_count($s,"call_user_func_array(array(\$classPeerName, 'retrieveByPk'), \$params)"));self::assertStringNotContainsString("implode( ',', \$params )",$s);}
public function testNativeDispatchContractPreservesArgumentsAndConstants():void{self::assertSame('fixture',constant(DynamicModelDispatchFixture::class.'::DATABASE_NAME'));self::assertSame(array('alpha',7),call_user_func_array(array(DynamicModelDispatchFixture::class,'retrieveByPk'),array('alpha',7)));$class=DynamicModelDispatchFixture::class;self::assertInstanceOf(DynamicModelDispatchFixture::class,new $class());}
public function testRatchetDropsSeventeenAndInventoryLeavesFiveFiles():void{$b=json_decode((string)file_get_contents(PM_TEST_ROOT.'/tests/fixtures/deprecation-budget.json'),true,512,JSON_THROW_ON_ERROR);$i=json_decode((string)file_get_contents(PM_TEST_ROOT.'/tests/fixtures/eval-inventory.json'),true,512,JSON_THROW_ON_ERROR);$c=CompatibilityLedger::counts($b['scope'],['eval'=>self::EVAL_PATTERN]);self::assertSame(0, $c['eval']['textual']);self::assertSame(0, $c['eval']['code']);self::assertSame(0, $b['budgets']['eval']);self::assertSame(0, $b['codeBudgets']['eval']);self::assertArrayHasKey('_noteU314',$b);self::assertSame(0, $i['summary']['executableFiles']);self::assertSame(0,$i['categories']['dynamic_model_or_criteria']['count']);foreach(self::TARGETS as$f){self::assertArrayNotHasKey($f,$i['perFileExecutable']);self::assertCount(0,array_filter($i['executableSites'],static fn(array$s):bool=>$s['file']===$f));}}
}
