<?php

declare(strict_types=1);
namespace Tests\Unit\Compatibility;
use PHPUnit\Framework\TestCase; use Tests\Support\CompatibilityLedger; use Tests\Support\PhpSourceScanner;
final class GulliverDirectDispatchEvalMigrationTest extends TestCase {
private const EVAL_PATTERN='(?<![\\w$>-])eval\\s*\\(';
private static function src(string $f):string{return PhpSourceScanner::read(PM_TEST_ROOT.'/'.$f);} private static function code(string $f):string{return PhpSourceScanner::codeOnlySource(self::src($f));}
private static function budget():array{return json_decode((string)file_get_contents(PM_TEST_ROOT.'/tests/fixtures/deprecation-budget.json'),true,512,JSON_THROW_ON_ERROR);} private static function inventory():array{return json_decode((string)file_get_contents(PM_TEST_ROOT.'/tests/fixtures/eval-inventory.json'),true,512,JSON_THROW_ON_ERROR);}
public function testBootstrapContainsNoExecutableEval():void{self::assertSame(0,PhpSourceScanner::matchCount(self::code('gulliver/system/class.bootstrap.php'),self::EVAL_PATTERN));}
public function testBootstrapUsesNativeDynamicTranslationVariables():void{$s=self::src('gulliver/system/class.bootstrap.php');self::assertStringContainsString("\$translationVariable = 'translation' . \$namePlugin;",$s);self::assertSame(2,substr_count($s,'global ${$translationVariable};'));self::assertStringContainsString('Bootstrap::json_encode(${$translationVariable})',$s);}
public function testGContainsNoExecutableEval():void{self::assertSame(0,PhpSourceScanner::matchCount(self::code('gulliver/system/class.g.php'),self::EVAL_PATTERN));}
public function testReplaceDataFieldFunctionDispatchUsesCallableApi():void{$s=self::src('gulliver/system/class.g.php');self::assertStringContainsString('$callable = $match[3][$r][0];',$s);self::assertStringContainsString('$argument = G::replaceDataField(stripslashes($match[4][$r][0]), $result);',$s);self::assertStringContainsString('$strAux = call_user_func($callable, $argument);',$s);}
public function testMessageSessionInterpolationUsesDirectArrayAccess():void{$s=self::src('gulliver/system/class.g.php');self::assertStringContainsString('$msg .= $_SESSION[$token];',$s);self::assertStringNotContainsString('eval("\\$msg.= \\$_SESSION',$s);}
public function testPluginTranslationUsesGlobalsArray():void{$s=self::src('gulliver/system/class.g.php');self::assertStringContainsString("\$translationVariable = 'translation' . \$namePlugin;",$s);self::assertStringContainsString('$existId = isset($GLOBALS[$translationVariable][$msgID]);',$s);self::assertStringContainsString('$GLOBALS[$translationVariable][$msgID]',$s);}
public function testWebResourceContainsNoExecutableEval():void{self::assertSame(0,PhpSourceScanner::matchCount(self::code('gulliver/system/class.webResource.php'),self::EVAL_PATTERN));}
public function testWebResourcePreservesPositionalReferencesForDispatch():void{$s=self::src('gulliver/system/class.webResource.php');self::assertStringContainsString('foreach (array_keys($parameters) as $key)',$s);self::assertStringContainsString('$arguments[] = &$parameters[$key];',$s);self::assertStringContainsString("\$res = call_user_func_array(array(\$this, \$post['function']), \$arguments);",$s);self::assertStringNotContainsString('$paramsRef',$s);}
public function testRatchetAndInventoryDropByNineAcrossThreeFiles():void{$b=self::budget();$c=CompatibilityLedger::counts($b['scope'],['eval'=>self::EVAL_PATTERN]);$i=self::inventory();self::assertSame(0, $c['eval']['textual']);self::assertSame(0, $c['eval']['code']);self::assertSame(0, $b['budgets']['eval']);self::assertSame(0, $b['codeBudgets']['eval']);self::assertArrayHasKey('_noteU312',$b);self::assertSame(0, $i['summary']['executableFiles']);self::assertSame(0,$i['categories']['gulliver_dynamic_runtime']['count']);foreach(['gulliver/system/class.bootstrap.php','gulliver/system/class.g.php','gulliver/system/class.webResource.php']as$f){self::assertArrayNotHasKey($f,$i['perFileExecutable']);self::assertCount(0,array_filter($i['executableSites'],static fn(array $s):bool=>$s['file']===$f));}}
}
