<?php

declare(strict_types=1);
namespace Tests\Unit\Compatibility;
use PHPUnit\Framework\TestCase; use Tests\Support\CompatibilityLedger; use Tests\Support\PhpSourceScanner;
require_once PM_TEST_ROOT.'/gulliver/system/class.xmlformSafeExpressionEvaluator.php';
final class GulliverFinalEvalMigrationTest extends TestCase {
private const EVAL_PATTERN='(?<![\\w$>-])eval\\s*\\(';
private static function src(string$f):string{return PhpSourceScanner::read(PM_TEST_ROOT.'/'.$f);} private static function code(string$f):string{return PhpSourceScanner::codeOnlySource(self::src($f));}
public function testEvaluatorHandlesBooleanAndNullLiterals():void{self::assertTrue(\XmlFormSafeExpressionEvaluator::evaluate('true'));self::assertFalse(\XmlFormSafeExpressionEvaluator::evaluate('false'));self::assertFalse(\XmlFormSafeExpressionEvaluator::evaluate('null'));}
public function testEvaluatorPreservesCellMarkStringEquality():void{self::assertTrue(\XmlFormSafeExpressionEvaluator::evaluate("'' == ''"));self::assertFalse(\XmlFormSafeExpressionEvaluator::evaluate("'2026-09-14' == ''"));self::assertTrue(\XmlFormSafeExpressionEvaluator::evaluate("'a' != 'b'"));}
public function testEvaluatorSupportsStrictAndRelationalComparisons():void{self::assertTrue(\XmlFormSafeExpressionEvaluator::evaluate('3 === 3'));self::assertFalse(\XmlFormSafeExpressionEvaluator::evaluate("'3' === 3"));self::assertTrue(\XmlFormSafeExpressionEvaluator::evaluate('2 < 3 && 4 >= 4'));}
public function testEvaluatorSupportsArithmeticAndParentheses():void{self::assertTrue(\XmlFormSafeExpressionEvaluator::evaluate('(2 + 3 * 4) == 14'));self::assertTrue(\XmlFormSafeExpressionEvaluator::evaluate('10 % 4 == 2'));self::assertFalse(\XmlFormSafeExpressionEvaluator::evaluate('1 / 0'));}
public function testEvaluatorSupportsBooleanPrecedenceAndXor():void{self::assertTrue(\XmlFormSafeExpressionEvaluator::evaluate('false || true && true'));self::assertTrue(\XmlFormSafeExpressionEvaluator::evaluate('true xor false'));self::assertFalse(\XmlFormSafeExpressionEvaluator::evaluate('true xor true'));}
public function testEvaluatorSupportsLiteralConcatenation():void{self::assertTrue(\XmlFormSafeExpressionEvaluator::evaluate("('a' . 'b') == 'ab'"));}
public function testEvaluatorFailsClosedForMalformedExpressions():void{self::assertFalse(\XmlFormSafeExpressionEvaluator::evaluate('('));self::assertFalse(\XmlFormSafeExpressionEvaluator::evaluate("'unterminated"));self::assertFalse(\XmlFormSafeExpressionEvaluator::evaluate('unknown_identifier'));}
public function testEvaluatorRejectsVariablesCallsAndObjectAccess():void{self::assertFalse(\XmlFormSafeExpressionEvaluator::evaluate('$GLOBALS'));self::assertFalse(\XmlFormSafeExpressionEvaluator::evaluate("phpinfo()"));self::assertFalse(\XmlFormSafeExpressionEvaluator::evaluate("system('id')"));self::assertFalse(\XmlFormSafeExpressionEvaluator::evaluate('$object->method()'));}
public function testXmlFormExtensionUsesOneSharedFailClosedEvaluator():void{$s=self::src('gulliver/system/class.xmlformExtension.php');self::assertSame(0,PhpSourceScanner::matchCount(self::code('gulliver/system/class.xmlformExtension.php'),self::EVAL_PATTERN));self::assertSame(2,substr_count($s,'XmlFormSafeExpressionEvaluator::evaluate($value);'));self::assertStringContainsString("require_once __DIR__ . '/class.xmlformSafeExpressionEvaluator.php';",$s);}
public function testRepositoryCellMarkConditionsFitRestrictedContract():void{$files=array_merge(glob(PM_TEST_ROOT.'/workflow/engine/xmlform/**/*.xml')?:array(),glob(PM_TEST_ROOT.'/workflow/engine/xmlform/*/*.xml')?:array());$seen=0;foreach(array_unique($files)as$f){$xml=(string)file_get_contents($f);if(preg_match_all('/type="cellMark"[^>]*condition="([^"]*)"/i',$xml,$m)){foreach($m[1]as$condition){++$seen;self::assertStringNotContainsString('(',html_entity_decode($condition,ENT_QUOTES,'UTF-8'));}}}self::assertGreaterThan(0,$seen);}
public function testTemplatePowerContainsNoExecutableEvalAndUsesTemporaryInclude():void{$s=self::src('gulliver/system/class.templatePower.php');self::assertSame(0,PhpSourceScanner::matchCount(self::code('gulliver/system/class.templatePower.php'),self::EVAL_PATTERN));self::assertStringContainsString('$temporaryScript = tmpfile();',$s);self::assertStringContainsString("include \$temporaryScriptMetadata['uri'];",$s);self::assertStringContainsString('finally {',$s);self::assertStringContainsString('fclose($temporaryScript);',$s);}
public function testTemplatePowerInlineScriptPreservesBufferedOutput():void{require_once PM_TEST_ROOT.'/gulliver/system/class.templatePower.php';$template="<!-- INCLUDESCRIPT BLOCK : sample -->\r\n";$parser=new \TemplatePower($template,T_BYVAR);$parser->assignInclude('sample',"before<?php echo strtoupper('ok'); ?>after",T_BYVAR);$parser->prepare();self::assertStringContainsString('beforeOKafter',$parser->getOutputContent());}
public function testRatchetClosesGulliverRuntimeCategory():void{$b=json_decode((string)file_get_contents(PM_TEST_ROOT.'/tests/fixtures/deprecation-budget.json'),true,512,JSON_THROW_ON_ERROR);$i=json_decode((string)file_get_contents(PM_TEST_ROOT.'/tests/fixtures/eval-inventory.json'),true,512,JSON_THROW_ON_ERROR);$c=CompatibilityLedger::counts($b['scope'],['eval'=>self::EVAL_PATTERN]);self::assertSame(0, $c['eval']['textual']);self::assertSame(0, $c['eval']['code']);self::assertSame(0, $b['budgets']['eval']);self::assertSame(0, $b['codeBudgets']['eval']);self::assertArrayHasKey('_noteU313',$b);self::assertSame(0, $i['summary']['executableFiles']);self::assertSame(0,$i['categories']['gulliver_dynamic_runtime']['count']);foreach(['gulliver/system/class.templatePower.php','gulliver/system/class.xmlformExtension.php']as$f){self::assertArrayNotHasKey($f,$i['perFileExecutable']);self::assertCount(0,array_filter($i['executableSites'],static fn(array$s):bool=>$s['file']===$f));}}
}
